site_name: MeteoGate Documentation
site_description: Documentation for MeteoGate Users, Data Publishers and Operators
site_author: EUMETNET
repo_url: https://github.com/EUMETNET/meteogate-documentation
theme:
  name: material
  language: en
  logo: eumetnet.png
  palette:
    primary: black
    accent: indigo
  font:
    text: Open Sans
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.highlight
    - content.code.copy

nav:
  - HOME: index.md
  - 1. OVERVIEW: 1-overview.md
  - 2. DISCOVERING AND ACCESSING DATA: 2-discovering-and-accessing-data.md
  - 3. PUBLISHING DATA: 3-publishing-data.md
  - 4. OPERATING COMMUNITY COMPONENTS: 4-operating-and-maintaining-community-components.md
  - ARCHITECTURE: technical-architecture.md
  - GLOSSARY: glossary.md
  - REFERENCES: references.md
